services:
  - type: web
    name: vossandthornellp
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn vossandthornellp.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: vossandthornellp.settings
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,vossandthornellp.org
