# Generated by Django 4.2.30 on 2026-05-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_address', models.CharField(max_length=500)),
                ('sender_phone', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_address', models.CharField(max_length=500)),
                ('receiver_phone', models.CharField(max_length=30)),
                ('receiver_email', models.CharField(max_length=254)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_country', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('dimensions', models.CharField(help_text='e.g. 40x30x20 cm', max_length=100)),
                ('cargo_type', models.CharField(choices=[('General', 'General'), ('Fragile', 'Fragile'), ('Perishable', 'Perishable'), ('Hazardous', 'Hazardous'), ('Electronics', 'Electronics')], default='General', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('On Hold', 'On Hold'), ('Exception', 'Exception')], default='Pending', max_length=20)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
