# Generated by Django 4.2.30 on 2026-09-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound (sent by us)'), ('inbound', 'Inbound (from client)')], max_length=10)),
                ('from_email', models.CharField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_email', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=998)),
                ('in_reply_to', models.CharField(blank=True, max_length=998)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_thread', to='tracking.shipment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
