# Generated by Django 4.2.30 on 2026-09-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_emailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='references',
            field=models.TextField(blank=True),
        ),
    ]
