# Generated by Django 4.2.30 on 2026-09-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_emailmessage_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
    ]
